export enum CardRenderItemType {
  TEMPERATURE = 'temperature',
  OXYGEN = 'oxygen',
  OCEANS = 'oceans',
  VENUS = 'venus',
  PLANTS = 'plants',
  TR = 'tr',
  HEAT = 'heat',
  ENERGY = 'energy',
  TITANIUM = 'titanium',
  STEEL = 'steel',
  MEGACREDITS = 'megacredits',
  CARDS = 'cards',
  FLOATERS = 'floaters',
  ASTEROIDS = 'asteroids',
  MICROBES = 'microbes',
  ANIMALS = 'animals',
  EVENT = 'event',
  SPACE = 'space',
  EARTH = 'earth',
  JOVIAN = 'jovian',
  TRADE = 'trade',
  TRADE_DISCOUNT = 'trade_discount',
  TRADE_FLEET = 'trade_fleet',
  CHAIRMAN = 'chairman',
  PARTY_LEADERS = 'party_leaders',
  DELEGATES = 'delegates',
  INFLUENCE = 'influence',
  NO_TAGS ='no_tags',
  WILD = 'wild',
  CITY = 'city',
  GREENERY = 'greenery',
  PLATE = 'plate',
  TEXT = 'text',
  NBSP = 'nbsp',
  // more to come...
}
