export enum CardRenderSymbolType {
  ASTERIX = '*',
  OR = 'OR',
  MINUS = '-',
  PLUS = '+',
  COLON = ':',
  EMPTY = ' ',
  SLASH = '/',
  ARROW = '->',
  BRACKET_OPEN = '(',
  BRACKET_CLOSE = ')',
  NBSP = 'nbsp',
  VSPACE = 'vspace',
  EQUALS = '=',
}
