import {DEFAULT_GAME_OPTIONS} from '../../src/server/game/GameOptions';
import {expect} from 'chai';
import {Hollandia} from '../../src/server/boards/Hollandia';
import {SeededRandom} from '../../src/common/utils/Random';

describe('HollandiaBoard', () => {
  it('sanity test', () => {
    const board = Hollandia.newInstance(DEFAULT_GAME_OPTIONS, new SeededRandom(0));
    expect(board.spaces).to.deep.eq([
      {id: '01', spaceType: 'colony', x: -1, y: -1, bonus: []},
      {id: '02', spaceType: 'colony', x: -1, y: -1, bonus: []},
      {id: '03', spaceType: 'ocean', x: 4, y: 0, bonus: [1]},
      {id: '04', spaceType: 'land', x: 5, y: 0, bonus: [2, 2]},
      {id: '05', spaceType: 'land', x: 6, y: 0, bonus: [3]},
      {id: '06', spaceType: 'ocean', x: 7, y: 0, bonus: [0]},
      {id: '07', spaceType: 'deflection', x: 8, y: 0, bonus: [2]},
      {id: '08', spaceType: 'ocean', x: 3, y: 1, bonus: [2, 2]},
      {id: '09', spaceType: 'land', x: 4, y: 1, bonus: [2, 2]},
      {id: '10', spaceType: 'land', x: 5, y: 1, bonus: []},
      {id: '11', spaceType: 'land', x: 6, y: 1, bonus: [1]},
      {id: '12', spaceType: 'deflection', x: 7, y: 1, bonus: []},
      {id: '13', spaceType: 'deflection', x: 8, y: 1, bonus: []},
      {id: '14', spaceType: 'land', x: 2, y: 2, bonus: [3]},
      {id: '15', spaceType: 'ocean', x: 3, y: 2, bonus: [2]},
      {id: '16', spaceType: 'land', x: 4, y: 2, bonus: [1, 2]},
      {id: '17', spaceType: 'land', x: 5, y: 2, bonus: []},
      {id: '18', spaceType: 'deflection', x: 6, y: 2, bonus: [2, 2]},
      {id: '19', spaceType: 'deflection', x: 7, y: 2, bonus: []},
      {id: '20', spaceType: 'deflection', x: 8, y: 2, bonus: [3]},
      {id: '21', spaceType: 'land', x: 1, y: 3, bonus: [1, 1, 1]},
      {id: '22', spaceType: 'land', x: 2, y: 3, bonus: [2]},
      {id: '23', spaceType: 'ocean', x: 3, y: 3, bonus: []},
      {id: '24', spaceType: 'land', x: 4, y: 3, bonus: [1, 2]},
      {id: '25', spaceType: 'land', x: 5, y: 3, bonus: []},
      {id: '26', spaceType: 'deflection', x: 6, y: 3, bonus: [0]},
      {id: '27', spaceType: 'deflection', x: 7, y: 3, bonus: []},
      {id: '28', spaceType: 'deflection', x: 8, y: 3, bonus: [1]},
      {id: '29', spaceType: 'land', x: 0, y: 4, bonus: [0]},
      {id: '30', spaceType: 'land', x: 1, y: 4, bonus: []},
      {id: '31', spaceType: 'land', x: 2, y: 4, bonus: [2]},
      {id: '32', spaceType: 'ocean', x: 3, y: 4, bonus: [2, 2]},
      {id: '33', spaceType: 'land', x: 4, y: 4, bonus: []},
      {id: '34', spaceType: 'land', x: 5, y: 4, bonus: []},
      {id: '35', spaceType: 'deflection', x: 6, y: 4, bonus: []},
      {id: '36', spaceType: 'deflection', x: 7, y: 4, bonus: [2]},
      {id: '37', spaceType: 'deflection', x: 8, y: 4, bonus: []},
      {id: '38', spaceType: 'land', x: 1, y: 5, bonus: [1, 2]},
      {id: '39', spaceType: 'land', x: 2, y: 5, bonus: []},
      {id: '40', spaceType: 'land', x: 3, y: 5, bonus: []},
      {id: '41', spaceType: 'land', x: 4, y: 5, bonus: [2, 1]},
      {id: '42', spaceType: 'land', x: 5, y: 5, bonus: []},
      {id: '43', spaceType: 'land', x: 6, y: 5, bonus: []},
      {id: '44', spaceType: 'land', x: 7, y: 5, bonus: [2, 2]},
      {id: '45', spaceType: 'ocean', x: 8, y: 5, bonus: [0, 0]},
      {id: '46', spaceType: 'ocean', x: 2, y: 6, bonus: [2, 2]},
      {id: '47', spaceType: 'land', x: 3, y: 6, bonus: []},
      {id: '48', spaceType: 'land', x: 4, y: 6, bonus: []},
      {id: '49', spaceType: 'land', x: 5, y: 6, bonus: [4, 4]},
      {id: '50', spaceType: 'land', x: 6, y: 6, bonus: [4, 4, 4]},
      {id: '51', spaceType: 'land', x: 7, y: 6, bonus: [2]},
      {id: '52', spaceType: 'ocean', x: 8, y: 6, bonus: [2]},
      {id: '53', spaceType: 'ocean', x: 3, y: 7, bonus: []},
      {id: '54', spaceType: 'ocean', x: 4, y: 7, bonus: [2, 2]},
      {id: '55', spaceType: 'land', x: 5, y: 7, bonus: [2, 2]},
      {id: '56', spaceType: 'land', x: 6, y: 7, bonus: [4, 4]},
      {id: '57', spaceType: 'land', x: 7, y: 7, bonus: [0, 2]},
      {id: '58', spaceType: 'ocean', x: 8, y: 7, bonus: [2]},
      {id: '59', spaceType: 'land', x: 4, y: 8, bonus: [3, 3]},
      {id: '60', spaceType: 'land', x: 5, y: 8, bonus: [2, 2]},
      {id: '61', spaceType: 'land', x: 6, y: 8, bonus: []},
      {id: '62', spaceType: 'land', x: 7, y: 8, bonus: []},
      {id: '63', spaceType: 'land', x: 8, y: 8, bonus: [3]},
    ]);
    expect(board.volcanicSpaceIds).deep.eq([]);
  });
});
