import {DEFAULT_GAME_OPTIONS} from '../../src/server/game/GameOptions';
import {expect} from 'chai';
import {UtopiaPlanitiaBoard} from '../../src/server/boards/UtopiaPlanitiaBoard';
import {SeededRandom} from '../../src/common/utils/Random';

describe('UtopiaPlanitiaBoard', () => {
  it('sanity test', () => {
    const board = UtopiaPlanitiaBoard.newInstance(DEFAULT_GAME_OPTIONS, new SeededRandom(0));
    expect(board.spaces).to.deep.eq([
      {'id': '01', 'spaceType': 'colony', 'x': -1, 'y': -1, 'bonus': []},
      {'id': '02', 'spaceType': 'colony', 'x': -1, 'y': -1, 'bonus': []},
      {'id': '03', 'spaceType': 'land', 'x': 4, 'y': 0, 'bonus': []},
      {'id': '04', 'spaceType': 'land', 'x': 5, 'y': 0, 'bonus': []},
      {'id': '05', 'spaceType': 'land', 'x': 6, 'y': 0, 'bonus': [9, 9]},
      {'id': '06', 'spaceType': 'land', 'x': 7, 'y': 0, 'bonus': []},
      {'id': '07', 'spaceType': 'land', 'x': 8, 'y': 0, 'bonus': []},
      {'id': '08', 'spaceType': 'land', 'x': 3, 'y': 1, 'bonus': []},
      {'id': '09', 'spaceType': 'land', 'x': 4, 'y': 1, 'bonus': [1, 1]},
      {'id': '10', 'spaceType': 'land', 'x': 5, 'y': 1, 'bonus': [9, 9]},
      {'id': '11', 'spaceType': 'land', 'x': 6, 'y': 1, 'bonus': [9, 9, 3]},
      {'id': '12', 'spaceType': 'land', 'x': 7, 'y': 1, 'bonus': []},
      {'id': '13', 'spaceType': 'land', 'x': 8, 'y': 1, 'bonus': []},
      {'id': '14', 'spaceType': 'ocean', 'x': 2, 'y': 2, 'bonus': [2, 2, 2]},
      {'id': '15', 'spaceType': 'land', 'x': 3, 'y': 2, 'bonus': []},
      {'id': '16', 'spaceType': 'land', 'x': 4, 'y': 2, 'bonus': [1]},
      {'id': '17', 'spaceType': 'land', 'x': 5, 'y': 2, 'bonus': []},
      {'id': '18', 'spaceType': 'land', 'x': 6, 'y': 2, 'bonus': []},
      {'id': '19', 'spaceType': 'land', 'x': 7, 'y': 2, 'bonus': [3, 3, 0]},
      {'id': '20', 'spaceType': 'land', 'x': 8, 'y': 2, 'bonus': [0, 0]},
      {'id': '21', 'spaceType': 'ocean', 'x': 1, 'y': 3, 'bonus': [2, 3]},
      {'id': '22', 'spaceType': 'land', 'x': 2, 'y': 3, 'bonus': [2]},
      {'id': '23', 'spaceType': 'land', 'x': 3, 'y': 3, 'bonus': [2]},
      {'id': '24', 'spaceType': 'land', 'x': 4, 'y': 3, 'bonus': [2, 2]},
      {'id': '25', 'spaceType': 'ocean', 'x': 5, 'y': 3, 'bonus': [2, 2]},
      {'id': '26', 'spaceType': 'ocean', 'x': 6, 'y': 3, 'bonus': [2]},
      {'id': '27', 'spaceType': 'ocean', 'x': 7, 'y': 3, 'bonus': [2]},
      {'id': '28', 'spaceType': 'land', 'x': 8, 'y': 3, 'bonus': [2]},
      {'id': '29', 'spaceType': 'land', 'x': 0, 'y': 4, 'bonus': []},
      {'id': '30', 'spaceType': 'land', 'x': 1, 'y': 4, 'bonus': []},
      {'id': '31', 'spaceType': 'land', 'x': 2, 'y': 4, 'bonus': []},
      {'id': '32', 'spaceType': 'land', 'x': 3, 'y': 4, 'bonus': [2]},
      {'id': '33', 'spaceType': 'land', 'x': 4, 'y': 4, 'bonus': [2]},
      {'id': '34', 'spaceType': 'land', 'x': 5, 'y': 4, 'bonus': [2, 2]},
      {'id': '35', 'spaceType': 'land', 'x': 6, 'y': 4, 'bonus': []},
      {'id': '36', 'spaceType': 'ocean', 'x': 7, 'y': 4, 'bonus': []},
      {'id': '37', 'spaceType': 'land', 'x': 8, 'y': 4, 'bonus': [2, 0]},
      {'id': '38', 'spaceType': 'land', 'x': 1, 'y': 5, 'bonus': [1]},
      {'id': '39', 'spaceType': 'land', 'x': 2, 'y': 5, 'bonus': [1, 1]},
      {'id': '40', 'spaceType': 'ocean', 'x': 3, 'y': 5, 'bonus': [2, 2]},
      {'id': '41', 'spaceType': 'land', 'x': 4, 'y': 5, 'bonus': [2, 2]},
      {'id': '42', 'spaceType': 'land', 'x': 5, 'y': 5, 'bonus': []},
      {'id': '43', 'spaceType': 'land', 'x': 6, 'y': 5, 'bonus': []},
      {'id': '44', 'spaceType': 'land', 'x': 7, 'y': 5, 'bonus': [1, 1]},
      {'id': '45', 'spaceType': 'land', 'x': 8, 'y': 5, 'bonus': []},
      {'id': '46', 'spaceType': 'land', 'x': 2, 'y': 6, 'bonus': [1]},
      {'id': '47', 'spaceType': 'land', 'x': 3, 'y': 6, 'bonus': []},
      {'id': '48', 'spaceType': 'ocean', 'x': 4, 'y': 6, 'bonus': []},
      {'id': '49', 'spaceType': 'ocean', 'x': 5, 'y': 6, 'bonus': [2, 2]},
      {'id': '50', 'spaceType': 'land', 'x': 6, 'y': 6, 'bonus': []},
      {'id': '51', 'spaceType': 'land', 'x': 7, 'y': 6, 'bonus': []},
      {'id': '52', 'spaceType': 'land', 'x': 8, 'y': 6, 'bonus': []},
      {'id': '53', 'spaceType': 'land', 'x': 3, 'y': 7, 'bonus': []},
      {'id': '54', 'spaceType': 'land', 'x': 4, 'y': 7, 'bonus': [3, 3]},
      {'id': '55', 'spaceType': 'ocean', 'x': 5, 'y': 7, 'bonus': []},
      {'id': '56', 'spaceType': 'ocean', 'x': 6, 'y': 7, 'bonus': [2, 2]},
      {'id': '57', 'spaceType': 'land', 'x': 7, 'y': 7, 'bonus': [1, 0]},
      {'id': '58', 'spaceType': 'land', 'x': 8, 'y': 7, 'bonus': [2, 2]},
      {'id': '59', 'spaceType': 'land', 'x': 4, 'y': 8, 'bonus': []},
      {'id': '60', 'spaceType': 'land', 'x': 5, 'y': 8, 'bonus': []},
      {'id': '61', 'spaceType': 'land', 'x': 6, 'y': 8, 'bonus': [1, 1]},
      {'id': '62', 'spaceType': 'ocean', 'x': 7, 'y': 8, 'bonus': [2]},
      {'id': '63', 'spaceType': 'land', 'x': 8, 'y': 8, 'bonus': [2]},
    ]);
  });
});
