
export enum PlayerInputTypes {
    AND_OPTIONS,
    OR_OPTIONS,
    SELECT_AMOUNT,
    SELECT_CARD,
    SELECT_DELEGATE,
    SELECT_HOW_TO_PAY,
    SELECT_HOW_TO_PAY_FOR_PROJECT_CARD,
    SELECT_INITIAL_CARDS,
    SELECT_OPTION,
    SELECT_PARTY_TO_SEND_DELEGATE,
    SELECT_PLAYER,
    SELECT_SPACE,
    SELECT_COLONY,
    SELECT_PRODUCTION_TO_LOSE,
    SHIFT_ARES_GLOBAL_PARAMETERS,
}
