import {PlayerInputType} from '../input/PlayerInputType';
import {CardModel} from './CardModel';
import {ColonyModel} from './ColonyModel';
import {ColorWithNeutral} from '../Color';
import {PayProductionModel} from './PayProductionUnitsModel';
import {AresData} from '../ares/AresData';
import {Message} from '../logs/Message';
import {PartyName} from '../turmoil/PartyName';
import {TurmoilModel} from './TurmoilModel';
import {TileType} from '../TileType';
import {SpaceId} from '../Types';
import {PaymentOptions} from '../inputs/Payment';

export interface PlayerInputModel {
    amount: number | undefined;
    availableSpaces: Array<SpaceId> | undefined;
    paymentOptions?: Partial<PaymentOptions>;
    cards: Array<CardModel> | undefined;
    inputType: PlayerInputType;
    options: Array<PlayerInputModel> | undefined;
    min: number | undefined;
    max: number | undefined;
    maxByDefault?: boolean;
    microbes: number | undefined;
    floaters: number | undefined;
    lunaArchivesScience: number | undefined;
    spireScience: number | undefined;
    seeds: number | undefined;
    auroraiData: number | undefined;
    graphene: number | undefined;
    kuiperAsteroids: number | undefined;
    players: Array<ColorWithNeutral> | undefined;
    title: string | Message;
    buttonLabel: string;
    coloniesModel : Array<ColonyModel> | undefined;
    payProduction?: PayProductionModel;
    aresData?: AresData;
    selectBlueCardAction: boolean;
    showOnlyInLearnerMode?: boolean;
    showOwner?: boolean;
    availableParties: Array<PartyName> | undefined;
    turmoil?: TurmoilModel;
    tiles?: Array<TileType>;
    showReset: boolean;
}
