export const awardNames = [
  'A. Zoologist',
  'Adapter',
  'Banker',
  'Benefactor',
  'Biologist',
  'Botanist',
  'Builder',
  'Businessperson',
  'Celebrity',
  'Contractor',
  'Coordinator',
  'Cosmic Settler',
  'Cultivator',
  'Curator',
  'Desert Settler',
  'Edgedancer',
  'Engineer',
  'Entrepreneur',
  'Estate Dealer',
  'Excentric',
  'Full Moon',
  'Historian',
  'Hoarder',
  'Industrialist',
  'Landlord',
  'Lunar Magnate',
  'Magnate',
  'Manufacturer',
  'Miner',
  'Naturalist',
  'Politician',
  'Scientist',
  'Space Baron',
  'T. Economizer',
  'Thermalist',
  'Tourist',
  'Urbanist',
  'Venuphile',
  'Voyager',
  'Warmonger',
  'Zoologist',
] as const;

export type AwardName = typeof awardNames[number];
