import {GameModule} from '../cards/GameModule';
import {AwardName} from './AwardName';
import {MilestoneName} from './MilestoneName';
import {BoardName} from '../boards/BoardName';
import {OneOrArray} from '../utils/types';

export type Details = {
  /* Components this MA needs to fucntion*/
  compatibility?: GameModule,
  /* Map or maps this is assigned to */
  map?: OneOrArray<BoardName>,
  /* If true, this is a modular MA. */
  modular?: boolean,
};

export const MACompatibility: Record<AwardName | MilestoneName, Details> = {
  'Landlord': {map: BoardName.THARSIS},
  'Scientist': {map: BoardName.THARSIS},
  'Banker': {map: BoardName.THARSIS},
  'Thermalist': {map: BoardName.THARSIS},
  'Miner': {map: BoardName.THARSIS},
  'Celebrity': {map: BoardName.ELYSIUM},
  'Industrialist': {map: BoardName.ELYSIUM},
  'Desert Settler': {map: BoardName.ELYSIUM},
  'Estate Dealer': {map: BoardName.ELYSIUM},
  'Benefactor': {map: BoardName.ELYSIUM},
  'Cultivator': {map: BoardName.HELLAS},
  'Excentric': {map: BoardName.HELLAS},
  'Magnate': {map: BoardName.HELLAS},
  'Space Baron': {map: BoardName.HELLAS},
  'Contractor': {map: BoardName.HELLAS},
  'Venuphile': {compatibility: 'venus'},
  'Entrepreneur': {compatibility: 'ares'},
  'Full Moon': {compatibility: 'moon'},
  'Lunar Magnate': {compatibility: 'moon'},
  'Curator': {map: BoardName.AMAZONIS},
  'Engineer': {map: BoardName.AMAZONIS},
  'Coordinator': {map: [BoardName.AMAZONIS, BoardName.ARABIA_TERRA]},
  'Tourist': {map: BoardName.AMAZONIS},
  'A. Zoologist': {map: BoardName.AMAZONIS},
  'Cosmic Settler': {map: BoardName.ARABIA_TERRA},
  'Botanist': {map: BoardName.ARABIA_TERRA},
  'Zoologist': {map: BoardName.ARABIA_TERRA},
  'A. Manufacturer': {map: BoardName.ARABIA_TERRA},
  'Biologist': {map: BoardName.TERRA_CIMMERIA},
  'T. Economizer': {map: BoardName.TERRA_CIMMERIA},
  'T. Politician': {map: BoardName.TERRA_CIMMERIA},
  'Urbanist': {map: BoardName.TERRA_CIMMERIA},
  'Warmonger': {map: BoardName.TERRA_CIMMERIA},
  'Adapter': {map: BoardName.VASTITAS_BOREALIS},
  'Edgedancer': {map: BoardName.VASTITAS_BOREALIS},
  'Hoarder': {map: BoardName.VASTITAS_BOREALIS},
  'Naturalist': {map: BoardName.VASTITAS_BOREALIS},
  'Voyager': {map: BoardName.VASTITAS_BOREALIS},
  'Kingpin': {compatibility: 'underworld'},
  'EdgeLord': {compatibility: 'underworld'},
  'Terraformer': {map: BoardName.THARSIS},
  'Mayor': {map: BoardName.THARSIS},
  'Gardener': {map: BoardName.THARSIS},
  'Planner': {map: BoardName.THARSIS},
  'Builder': {map: BoardName.THARSIS},
  'Generalist': {map: BoardName.ELYSIUM},
  'Specialist': {map: BoardName.ELYSIUM},
  'Ecologist': {map: BoardName.ELYSIUM},
  'Tycoon': {map: BoardName.ELYSIUM},
  'Legend': {map: BoardName.ELYSIUM},
  'Diversifier': {map: BoardName.HELLAS},
  'Tactician': {map: BoardName.HELLAS},
  'Polar Explorer': {map: BoardName.HELLAS},
  'Energizer': {map: BoardName.HELLAS},
  'Rim Settler': {map: BoardName.HELLAS},
  'Hoverlord': {compatibility: 'venus'},
  'Networker': {compatibility: 'ares'},
  'One Giant Step': {compatibility: 'moon'},
  'Lunarchitect': {compatibility: 'moon'},
  'Colonizer': {map: BoardName.AMAZONIS},
  'Farmer': {map: BoardName.AMAZONIS},
  'Minimalist': {map: BoardName.AMAZONIS},
  'Terran': {map: BoardName.AMAZONIS},
  'Tropicalist': {map: BoardName.AMAZONIS},
  'Economizer': {map: BoardName.ARABIA_TERRA},
  'Pioneer': {map: BoardName.ARABIA_TERRA},
  'Land Specialist': {map: BoardName.ARABIA_TERRA},
  'Martian': {map: BoardName.ARABIA_TERRA},
  'Businessperson': {map: BoardName.ARABIA_TERRA},
  'T. Collector': {map: BoardName.TERRA_CIMMERIA},
  'Firestarter': {map: BoardName.TERRA_CIMMERIA},
  'Terra Pioneer': {map: BoardName.TERRA_CIMMERIA},
  'Spacefarer': {map: BoardName.TERRA_CIMMERIA},
  'Gambler': {map: BoardName.TERRA_CIMMERIA},
  'V. Electrician': {map: BoardName.VASTITAS_BOREALIS},
  'Smith': {map: BoardName.VASTITAS_BOREALIS},
  'Tradesman': {map: BoardName.VASTITAS_BOREALIS},
  'Irrigator': {map: BoardName.VASTITAS_BOREALIS},
  'Capitalist': {map: BoardName.VASTITAS_BOREALIS},
  'Tunneler': {compatibility: 'underworld'},
  'Risktaker': {compatibility: 'underworld'},
  'Administrator': {modular: true},
  'Constructor': {modular: true},
  'Investor': {modular: true},
  'Mogul': {modular: true},
  'Traveller': {modular: true},
  'Fundraiser': {modular: true},
  'Philantropist': {modular: true},
  'Producer': {modular: true},
  'Researcher': {modular: true},
  'Sponsor': {modular: true},
};
