export const milestoneNames = [
  'Builder',
  'Businessperson',
  'Capitalist',
  'Collector',
  'Colonizer',
  'Diversifier',
  'Ecologist',
  'Economizer',
  'Electrician',
  'Energizer',
  'Farmer',
  'Firestarter',
  'Gambler',
  'Gardener',
  'Generalist',
  'Hoverlord',
  'Irrigator',
  'Land Specialist',
  'Legend',
  'Lunarchitect',
  'Martian',
  'Mayor',
  'Minimalist',
  'Networker',
  'One Giant Step',
  'Pioneer',
  'Planner',
  'Polar Explorer',
  'Rim Settler',
  'Smith',
  'Spacefarer',
  'Specialist',
  'Tactician',
  'Terra Pioneer',
  'Terraformer',
  'Terran',
  'Tradesman',
  'Tropicalist',
  'Tycoon',
] as const;

export type MilestoneName = typeof milestoneNames[number];
