export enum GlobalEventName {
    GLOBAL_DUST_STORM = 'Global Dust Storm',
    SPONSORED_PROJECTS = 'Sponsored Projects',
    ASTEROID_MINING = 'Asteroid Mining',
    GENEROUS_FUNDING = 'Generous Funding',
    SUCCESSFUL_ORGANISMS = 'Successful Organisms',
    ECO_SABOTAGE = 'Eco Sabotage',
    PRODUCTIVITY = 'Productivity',
    SNOW_COVER = 'Snow Cover',
    DIVERSITY = 'Diversity',
    PANDEMIC = 'Pandemic',
    WAR_ON_EARTH = 'War on Earth',
    IMPROVED_ENERGY_TEMPLATES = 'Improved Energy Templates',
    INTERPLANETARY_TRADE = 'Interplanetary Trade',
    CELEBRITY_LEADERS = 'Celebrity Leaders',
    SPINOFF_PRODUCTS = 'Spin-Off Products',
    ELECTION = 'Election',
    AQUIFER_RELEASED_BY_PUBLIC_COUNCIL = 'Aquifer Released by Public Council',
    PARADIGM_BREAKDOWN = 'Paradigm Breakdown',
    HOMEWORLD_SUPPORT = 'Homeworld Support',
    RIOTS = 'Riots',
    VOLCANIC_ERUPTIONS = 'Volcanic Eruptions',
    MUD_SLIDES = 'Mud Slides',
    MINERS_ON_STRIKE = 'Miners On Strike',
    SABOTAGE = 'Sabotage',
    REVOLUTION = 'Revolution',
    DRY_DESERTS = 'Dry Deserts',
    SCIENTIFIC_COMMUNITY = 'Scientific Community',
    CORROSIVE_RAIN = 'Corrosive Rain',
    JOVIAN_TAX_RIGHTS = 'Jovian Tax Rights',
    RED_INFLUENCE = 'Red Influence',
    SOLARNET_SHUTDOWN = 'Solarnet Shutdown',
    STRONG_SOCIETY = 'Strong Society',
    SOLAR_FLARE = 'Solar Flare',
    VENUS_INFRASTRUCTURE = 'Venus Infrastructure',
    CLOUD_SOCIETIES = 'Cloud Societies',
    MICROGRAVITY_HEALTH_PROBLEMS = 'Microgravity Health Problems',

    // Community
    LEADERSHIP_SUMMIT = 'Leadership Summit',

    // Pathfinders
    BALANCED_DEVELOPMENT = 'Balanced Development',
    CONSTANT_STRUGGLE = 'Constant Struggle',
    TIRED_EARTH = 'Tired Earth',
    MAGNETIC_FIELD_STIMULATION_DELAYS ='Magnetic Field Stimulation Delays',
    COMMUNICATION_BOOM = 'Communication Boom',
    SPACE_RACE_TO_MARS = 'Space Race to Mars',
}
