import {ColonyName} from './ColonyName';

export const COLONY_DESCRIPTIONS: Record<ColonyName, string> = {
  [ColonyName.CALLISTO]: 'Energy',
  [ColonyName.CERES]: 'Steel',
  [ColonyName.ENCELADUS]: 'Microbes',
  [ColonyName.EUROPA]: 'Production',
  [ColonyName.GANYMEDE]: 'Plants',
  [ColonyName.IO]: 'Heat',
  [ColonyName.LUNA]: 'MegaCredits',
  [ColonyName.MIRANDA]: 'Animals',
  [ColonyName.PLUTO]: 'Cards',
  [ColonyName.TITAN]: 'Floaters',
  [ColonyName.TRITON]: 'Titanium',
  [ColonyName.IAPETUS]: 'TR',
  [ColonyName.MERCURY]: 'Production',
  [ColonyName.HYGIEA]: 'Attack',
  [ColonyName.TITANIA]: 'VP',
  [ColonyName.VENUS]: 'Venus',
  [ColonyName.LEAVITT]: 'Science',
  [ColonyName.PALLAS]: 'Politics',
  [ColonyName.LEAVITT_II]: 'Science & Clone Tags',
  [ColonyName.IAPETUS_II]: 'Data',
  [ColonyName.DEIMOS]: 'Hazards',
};
