
export enum PlayerInputTypes {
    AND_OPTIONS,
    OR_OPTIONS,
    SELECT_AMOUNT,
    SELECT_CARD,
    SELECT_HOW_TO_PAY,
    SELECT_HOW_TO_PAY_FOR_CARD,
    SELECT_OPTION,
    SELECT_PLAYER,
    SELECT_SPACE,
    SELECT_DELEGATE,
    SELECT_PARTY
}
