import {PlayerId} from './Player';
import {CardName} from './CardName';
import {Color} from './Color';
import {SerializedCard} from './SerializedCard';
import {VictoryPointsBreakdown} from './VictoryPointsBreakdown';
import {Timer} from './Timer';
import {CorporationCard} from './cards/corporation/CorporationCard';

// TODO(kberg): remove reference to CorporationCard by 2021-01-15
export interface SerializedPlayer {
    actionsTakenThisRound: number;
    actionsThisGeneration: Array<string>;
    beginner: boolean;
    canUseHeatAsMegaCredits: boolean;
    cardCost: number;
    cardDiscount: number;
    cardsInHand: Array<CardName>;
    colonyTradeDiscount: number;
    colonyTradeOffset: number;
    colonyVictoryPoints: number;
    color: Color;
    corporationCard: SerializedCard | undefined;
    corporationInitialActionDone: boolean;
    dealtCorporationCards: Array<CardName>;
    dealtPreludeCards: Array<CardName>;
    dealtProjectCards: Array<CardName>;
    draftedCards: Array<CardName>;
    energy: number;
    energyProduction: number;
    fleetSize: number;
    generationPlayed: Array<[string, number]>;
    handicap: number;
    hasIncreasedTerraformRatingThisGeneration: boolean;
    heat: number;
    heatProduction: number;
    id: string;
    lastCardPlayed?: CardName;
    megaCreditProduction: number;
    megaCredits: number;
    name: string;
    needsToDraft: boolean | undefined;
    oceanBonus: number;
    pickedCorporationCard: CardName | CorporationCard | undefined;
    plantProduction: number;
    plants: number;
    plantsNeededForGreenery: number;
    playedCards: Array<SerializedCard>;
    powerPlantCost: number;
    preludeCardsInHand: Array<CardName>;
    removedFromPlayCards: Array<CardName>;
    removingPlayers: Array<PlayerId>;
    scienceTagCount: number;
    shouldTriggerCardEffect: boolean;
    steel: number;
    steelProduction: number;
    steelValue: number;
    terraformRating: number;
    terraformRatingAtGenerationStart: number;
    timer: Timer;
    titanium: number;
    titaniumProduction: number;
    titaniumValue: number;
    tradesThisTurn: number;
    usedUndo: boolean;
    turmoilScientistsActionUsed: boolean;
    victoryPointsBreakdown: VictoryPointsBreakdown;
}
