import {IProjectCard} from './cards/IProjectCard';
import {CorporationCard} from './cards/corporation/CorporationCard';
import {PlayerId} from './Player';
import {CardName} from './CardName';
import {Color} from './Color';
import {SerializedCard} from './SerializedCard';
import {VictoryPointsBreakdown} from './VictoryPointsBreakdown';

export interface SerializedPlayer {
    actionsTakenThisRound: number;
    actionsThisGeneration: Array<string>;
    beginner: boolean;
    canUseHeatAsMegaCredits: boolean;
    cardCost: number;
    cardDiscount: number;
    cardsInHand: Array<CardName> | Array<IProjectCard>;
    colonyTradeDiscount: number;
    colonyTradeOffset: number;
    colonyVictoryPoints: number;
    color: Color;
    corporationCard: SerializedCard | undefined;
    corporationInitialActionDone: boolean;
    dealtCorporationCards: Array<CardName> | Array<CorporationCard>;
    dealtPreludeCards: Array<CardName> | Array<IProjectCard>;
    dealtProjectCards: Array<CardName> | Array<IProjectCard>;
    draftedCards: Array<CardName> | Array<IProjectCard>;
    energy: number;
    energyProduction: number;
    fleetSize: number;
    generationPlayed: Array<[string, number]>;
    handicap: number;
    hasIncreasedTerraformRatingThisGeneration: boolean;
    heat: number;
    heatProduction: number;
    id: string;
    lastCardPlayed?: CardName | IProjectCard;
    megaCreditProduction: number;
    megaCredits: number;
    name: string;
    needsToDraft: boolean | undefined;
    oceanBonus: number;
    pickedCorporationCard: CardName | CorporationCard | undefined;
    plantProduction: number;
    plants: number;
    plantsNeededForGreenery: number;
    playedCards: Array<SerializedCard>;
    powerPlantCost: number;
    preludeCardsInHand: Array<CardName> | Array<IProjectCard>;
    removedFromPlayCards: Array<CardName> | Array<IProjectCard>;
    removingPlayers: Array<PlayerId>;
    scienceTagCount: number;
    shouldTriggerCardEffect: boolean;
    steel: number;
    steelProduction: number;
    steelValue: number;
    terraformRating: number;
    terraformRatingAtGenerationStart: number;
    titanium: number;
    titaniumProduction: number;
    titaniumValue: number;
    tradesThisTurn: number;
    turmoilPolicyActionUsed: boolean;
    victoryPointsBreakdown: VictoryPointsBreakdown;
}
