
export enum SpaceName {
    GANYMEDE_COLONY = "GANYMEDE_COLONY",
    THARSIS_THOLUS = "THARSIS_THOLUS",
    ASCRAEUS_MONS = "ARCRAEUS_MONS",
    PAVONIS_MONS = "PAVONIS_MONS",
    ARSIA_MONS = "ARSIA_MONS"
}
