
export enum SpaceName {
    ARSIA_MONS = "ARSIA_MONS",
    ASCRAEUS_MONS = "ARCRAEUS_MONS",
    GANYMEDE_COLONY = "GANYMEDE_COLONY",
    NOCTIS_CITY = "NOCTIS_CITY",
    PAVONIS_MONS = "PAVONIS_MONS",
    PHOBOS_SPACE_HAVEN = "PHOBOS_SPACE_HAVEN",
    THARSIS_THOLUS = "THARSIS_THOLUS"
}
