
export enum TileType {
    GREENERY,
    OCEAN,
    CITY,
    
    CAPITAL,
    COMMERCIAL_DISTRICT,
    ECOLOGICAL_ZONE,
    INDUSTRIAL_CENTER,
    LAVA_FLOWS,
    MINING_AREA,
    MINING_RIGHTS,
    MOHOLE_AREA,
    NATURAL_PRESERVE,
    NUCLEAR_ZONE,
    RESTRICTED_AREA,

    DEIMOS_DOWN,
    GREAT_DAM,
    MAGNETIC_FIELD_GENERATORS
}
