export enum CardResource {
    ANIMAL = 'Animal',
    MICROBE = 'Microbe',
    FIGHTER = 'Fighter',
    SCIENCE = 'Science',
    FLOATER = 'Floater',
    ASTEROID = 'Asteroid',
    PRESERVATION = 'Preservation',
    CAMP = 'Camp',
    DISEASE = 'Disease',
    RESOURCE_CUBE = 'Resource cube',
    DATA = 'Data',
    SYNDICATE_FLEET = 'Syndicate Fleet',
    VENUSIAN_HABITAT = 'Venusian Habitat',
    SPECIALIZED_ROBOT = 'Specialized Robot',
    SEED = 'Seed',
    AGENDA = 'Agenda',
    ORBITAL = 'Orbital',
}
