export enum RequirementType {
    OXYGEN = "O2",
    TEMPERATURE = "C",
    OCEANS = "Ocean",
    VENUS = "Venus",
    TR = "TR",
    RESOURCE_TYPES = "Resource type",
    FORESTS = "Forest",
    CITIES = "City",
    COLONIES = "Colony",
    FLOATERS = "Floater",
    TAG = "tag",
    PRODUCTION = "production",
    TRADE = "Trade",
    TRADE_FLEET = "Trade fleet",
    TRADE_DISCOUNT = "Trade discount",
    INFLUENCE = "Influence",
    CHAIRMAN = "Chairman",
    PARTY_LEADERS = "Party leader",
    PARTY = "party",
    DELEGATES = "Delegate",
}
