export enum RequirementType {
    OXYGEN = "O2",
    TEMPERATURE = "C",
    OCEANS = "Ocean",
    VENUS = "Venus",
    TR = "TR",
    RESOURCE_TYPES = "Resource type",
    FORESTS = "Forest",
    CITIES = "City",
    COLONIES = "Colony",
    FLOATERS = "Floater",
    CHAIRMAN = "Chairman",

    TAG_SCIENCE = "science",
    TAG_PLANT = "plant",
    TAG_MICROBE = "microbe",
    TAG_ANIMAL = "animal",
    TAG_BUILDING = "building",
    TAG_SPACE = "space",
    TAG_ENERGY = "power",
    TAG_EARTH = "earth",
    TAG_JOVIAN = "jovian",
    TAG_VENUS = "venus",
    TAG_CITY = "city",
    TAG_EVENT = "event",
    PROD_TITANIUM = "titanium production",
    PROD_STEEL = "steel production",
    PROD_PLANTS = "plants production",
    PROD_HEAT = "heat production",
    PROD_ENERGY = "energy production",
    RULING_KELVINISTS = "kelvinists",
    RULING_SCIENTISTS = "scientists",
    RULING_GREENS = "greens",
    RULING_REDS = "reds",
    RULING_MARS = "mars",
    RULING_UNITY = "unity", 
}
