import {CardName} from '../common/cards/CardName';
import {AcquiredCompany} from './base/AcquiredCompany';
import {AdaptationTechnology} from './base/AdaptationTechnology';
import {AdaptedLichen} from './base/AdaptedLichen';
import {AdvancedAlloys} from './base/AdvancedAlloys';
import {AdvancedEcosystems} from './base/AdvancedEcosystems';
import {AerobrakedAmmoniaAsteroid} from './base/AerobrakedAmmoniaAsteroid';
import {AICentral} from './base/AICentral';
import {Algae} from './base/Algae';
import {AntiGravityTechnology} from './base/AntiGravityTechnology';
import {Ants} from './base/Ants';
import {AquiferPumping} from './base/AquiferPumping';
import {ArchaeBacteria} from './base/ArchaeBacteria';
import {ArcticAlgae} from './base/ArcticAlgae';
import {ArtificialLake} from './base/ArtificialLake';
import {ArtificialPhotosynthesis} from './base/ArtificialPhotosynthesis';
import {Asteroid} from './base/Asteroid';
import {AsteroidMining} from './base/AsteroidMining';
import {AsteroidMiningConsortium} from './base/AsteroidMiningConsortium';
import {BeamFromAThoriumAsteroid} from './base/BeamFromAThoriumAsteroid';
import {BeginnerCorporation} from './corporation/BeginnerCorporation';
import {BigAsteroid} from './base/BigAsteroid';
import {BiomassCombustors} from './base/BiomassCombustors';
import {Birds} from './base/Birds';
import {BlackPolarDust} from './base/BlackPolarDust';
import {BreathingFilters} from './base/BreathingFilters';
import {BribedCommittee} from './base/BribedCommittee';
import {BuildingIndustries} from './base/BuildingIndustries';
import {Bushes} from './base/Bushes';
import {BusinessContacts} from './base/BusinessContacts';
import {BusinessNetwork} from './base/BusinessNetwork';
import {CallistoPenalMines} from './base/CallistoPenalMines';
import {Capital} from './base/Capital';
import {CarbonateProcessing} from './base/CarbonateProcessing';
import {CardManifest} from './CardManifest';
import {CaretakerContract} from './base/CaretakerContract';
import {Cartel} from './base/Cartel';
import {CEOsFavoriteProject} from './base/CEOsFavoriteProject';
import {CloudSeeding} from './base/CloudSeeding';
import {ColonizerTrainingCamp} from './base/ColonizerTrainingCamp';
import {Comet} from './base/Comet';
import {CommercialDistrict} from './base/CommercialDistrict';
import {ConvoyFromEuropa} from './base/ConvoyFromEuropa';
import {CorporateStronghold} from './base/CorporateStronghold';
import {CrediCor} from './corporation/CrediCor';
import {EcoLine} from './corporation/EcoLine';
import {Helion} from './corporation/Helion';
import {InterplanetaryCinematics} from './corporation/InterplanetaryCinematics';
import {Inventrix} from './corporation/Inventrix';
import {MiningGuild} from './corporation/MiningGuild';
import {PhoboLog} from './corporation/PhoboLog';
import {SaturnSystems} from './corporation/SaturnSystems';
import {Teractor} from './corporation/Teractor';
import {TharsisRepublic} from './corporation/TharsisRepublic';
import {Thorgate} from './corporation/Thorgate';
import {UnitedNationsMarsInitiative} from './corporation/UnitedNationsMarsInitiative';
import {CupolaCity} from './base/CupolaCity';
import {Decomposers} from './base/Decomposers';
import {DeepWellHeating} from './base/DeepWellHeating';
import {DeimosDown} from './base/DeimosDown';
import {DesignedMicroOrganisms} from './base/DesignedMicroOrganisms';
import {DevelopmentCenter} from './base/DevelopmentCenter';
import {DomedCrater} from './base/DomedCrater';
import {DustSeals} from './base/DustSeals';
import {EarthCatapult} from './base/EarthCatapult';
import {EarthOffice} from './base/EarthOffice';
import {EcologicalZone} from './base/EcologicalZone';
import {ElectroCatapult} from './base/ElectroCatapult';
import {EnergySaving} from './base/EnergySaving';
import {EnergyTapping} from './base/EnergyTapping';
import {EosChasmaNationalPark} from './base/EOSChasmaNationalPark';
import {EquatorialMagnetizer} from './base/EquatorialMagnetizer';
import {ExtremeColdFungus} from './base/ExtremeColdFungus';
import {Farming} from './base/Farming';
import {Fish} from './base/Fish';
import {Flooding} from './base/Flooding';
import {FoodFactory} from './base/FoodFactory';
import {FueledGenerators} from './base/FueledGenerators';
import {FuelFactory} from './base/FuelFactory';
import {FusionPower} from './base/FusionPower';
import {GanymedeColony} from './base/GanymedeColony';
import {GeneRepair} from './base/GeneRepair';
import {GeothermalPower} from './base/GeothermalPower';
import {GHGFactories} from './base/GHGFactories';
import {GHGProducingBacteria} from './base/GHGProducingBacteria';
import {GiantIceAsteroid} from './base/GiantIceAsteroid';
import {GiantSpaceMirror} from './base/GiantSpaceMirror';
import {Grass} from './base/Grass';
import {GreatDam} from './base/GreatDam';
import {GreatEscarpmentConsortium} from './base/GreatEscarpmentConsortium';
import {Greenhouses} from './base/Greenhouses';
import {Hackers} from './base/Hackers';
import {Heather} from './base/Heather';
import {HeatTrappers} from './base/HeatTrappers';
import {Herbivores} from './base/Herbivores';
import {HiredRaiders} from './base/HiredRaiders';
import {IceAsteroid} from './base/IceAsteroid';
import {IceCapMelting} from './base/IceCapMelting';
import {ImmigrantCity} from './base/ImmigrantCity';
import {ImmigrationShuttles} from './base/ImmigrationShuttles';
import {ImportedGHG} from './base/ImportedGHG';
import {ImportedHydrogen} from './base/ImportedHydrogen';
import {ImportedNitrogen} from './base/ImportedNitrogen';
import {ImportOfAdvancedGHG} from './base/ImportOfAdvancedGHG';
import {IndenturedWorkers} from './base/IndenturedWorkers';
import {IndustrialCenter} from './base/IndustrialCenter';
import {IndustrialMicrobes} from './base/IndustrialMicrobes';
import {Insects} from './base/Insects';
import {Insulation} from './base/Insulation';
import {InterstellarColonyShip} from './base/InterstellarColonyShip';
import {InventionContest} from './base/InventionContest';
import {InventorsGuild} from './base/InventorsGuild';
import {InvestmentLoan} from './base/InvestmentLoan';
import {IoMiningIndustries} from './base/IoMiningIndustries';
import {Ironworks} from './base/Ironworks';
import {KelpFarming} from './base/KelpFarming';
import {LagrangeObservatory} from './base/LagrangeObservatory';
import {LakeMarineris} from './base/LakeMarineris';
import {LandClaim} from './base/LandClaim';
import {LargeConvoy} from './base/LargeConvoy';
import {LavaFlows} from './base/LavaFlows';
import {Lichen} from './base/Lichen';
import {LightningHarvest} from './base/LightningHarvest';
import {Livestock} from './base/Livestock';
import {LocalHeatTrapping} from './base/LocalHeatTrapping';
import {LunarBeam} from './base/LunarBeam';
import {MagneticFieldDome} from './base/MagneticFieldDome';
import {MagneticFieldGenerators} from './base/MagneticFieldGenerators';
import {Mangrove} from './base/Mangrove';
import {MarsUniversity} from './base/MarsUniversity';
import {MartianRails} from './base/MartianRails';
import {MassConverter} from './base/MassConverter';
import {MediaArchives} from './base/MediaArchives';
import {MediaGroup} from './base/MediaGroup';
import {MedicalLab} from './base/MedicalLab';
import {MethaneFromTitan} from './base/MethaneFromTitan';
import {MicroMills} from './base/MicroMills';
import {Mine} from './base/Mine';
import {MineralDeposit} from './base/MineralDeposit';
import {MiningArea} from './base/MiningArea';
import {MiningExpedition} from './base/MiningExpedition';
import {MiningRights} from './base/MiningRights';
import {MirandaResort} from './base/MirandaResort';
import {MoholeArea} from './base/MoholeArea';
import {Moss} from './base/Moss';
import {NaturalPreserve} from './base/NaturalPreserve';
import {NitriteReducingBacteria} from './base/NitriteReducingBacteria';
import {NitrogenRichAsteroid} from './base/NitrogenRichAsteroid';
import {NitrophilicMoss} from './base/NitrophilicMoss';
import {NoctisCity} from './base/NoctisCity';
import {NoctisFarming} from './base/NoctisFarming';
import {NuclearPower} from './base/NuclearPower';
import {NuclearZone} from './base/NuclearZone';
import {OlympusConference} from './base/OlympusConference';
import {OpenCity} from './base/OpenCity';
import {OptimalAerobraking} from './base/OptimalAerobraking';
import {OreProcessor} from './base/OreProcessor';
import {PermafrostExtraction} from './base/PermafrostExtraction';
import {PeroxidePower} from './base/PeroxidePower';
import {Pets} from './base/Pets';
import {PhobosSpaceHaven} from './base/PhobosSpaceHaven';
import {PhysicsComplex} from './base/PhysicsComplex';
import {Plantation} from './base/Plantation';
import {PowerGrid} from './base/PowerGrid';
import {PowerInfrastructure} from './base/PowerInfrastructure';
import {PowerPlant} from './base/PowerPlant';
import {PowerSupplyConsortium} from './base/PowerSupplyConsortium';
import {Predators} from './base/Predators';
import {ProtectedHabitats} from './base/ProtectedHabitats';
import {ProtectedValley} from './base/ProtectedValley';
import {QuantumExtractor} from './base/QuantumExtractor';
import {RadChemFactory} from './base/RadChemFactory';
import {RadSuits} from './base/RadSuits';
import {RegolithEaters} from './base/RegolithEaters';
import {ReleaseOfInertGases} from './base/ReleaseOfInertGases';
import {Research} from './base/Research';
import {ResearchOutpost} from './base/ResearchOutpost';
import {RestrictedArea} from './base/RestrictedArea';
import {RoboticWorkforce} from './base/RoboticWorkforce';
import {RoverConstruction} from './base/RoverConstruction';
import {Sabotage} from './base/Sabotage';
import {Satellites} from './base/Satellites';
import {SearchForLife} from './base/SearchForLife';
import {SecurityFleet} from './base/SecurityFleet';
import {Shuttles} from './base/Shuttles';
import {SmallAnimals} from './base/SmallAnimals';
import {SoilFactory} from './base/SoilFactory';
import {SolarPower} from './base/SolarPower';
import {SolarWindPower} from './base/SolarWindPower';
import {Soletta} from './base/Soletta';
import {SpaceElevator} from './base/SpaceElevator';
import {SpaceMirrors} from './base/SpaceMirrors';
import {SpaceStation} from './base/SpaceStation';
import {SpecialDesign} from './base/SpecialDesign';
import {Sponsors} from './base/Sponsors';
import {StandardTechnology} from './base/StandardTechnology';
import {Steelworks} from './base/Steelworks';
import {StripMine} from './base/StripMine';
import {SubterraneanReservoir} from './base/SubterraneanReservoir';
import {SymbioticFungus} from './base/SymbioticFungus';
import {Tardigrades} from './base/Tardigrades';
import {TechnologyDemonstration} from './base/TechnologyDemonstration';
import {TectonicStressPower} from './base/TectonicStressPower';
import {TerraformingGanymede} from './base/TerraformingGanymede';
import {TitaniumMine} from './base/TitaniumMine';
import {TollStation} from './base/TollStation';
import {TowingAComet} from './base/TowingAComet';
import {TransNeptuneProbe} from './base/TransNeptuneProbe';
import {Trees} from './base/Trees';
import {TropicalResort} from './base/TropicalResort';
import {TundraFarming} from './base/TundraFarming';
import {UndergroundCity} from './base/UndergroundCity';
import {UndergroundDetonations} from './base/UndergroundDetonations';
import {UrbanizedArea} from './base/UrbanizedArea';
import {VestaShipyard} from './base/VestaShipyard';
import {ViralEnhancers} from './base/ViralEnhancers';
import {Virus} from './base/Virus';
import {WaterImportFromEuropa} from './base/WaterImportFromEuropa';
import {WaterSplittingPlant} from './base/WaterSplittingPlant';
import {WavePower} from './base/WavePower';
import {Windmills} from './base/Windmills';
import {Worms} from './base/Worms';
import {Zeppelins} from './base/Zeppelins';
import {AquiferStandardProject} from './base/standardProjects/AquiferStandardProject';
import {CityStandardProject} from './base/standardProjects/CityStandardProject';
import {PowerPlantStandardProject} from './base/standardProjects/PowerPlantStandardProject';
import {GreeneryStandardProject} from './base/standardProjects/GreeneryStandardProject';
import {AsteroidStandardProject} from './base/standardProjects/AsteroidStandardProject';
import {SellPatentsStandardProject} from './base/standardProjects/SellPatentsStandardProject';
import {ConvertPlants} from './base/standardActions/ConvertPlants';
import {ConvertHeat} from './base/standardActions/ConvertHeat';
import {BufferGasStandardProject} from './prelude/BufferGasStandardProject';

export const BASE_CARD_MANIFEST = new CardManifest({
  module: 'base',
  projectCards: [
    {cardName: CardName.ADAPTATION_TECHNOLOGY, Factory: AdaptationTechnology},
    {cardName: CardName.ADAPTED_LICHEN, Factory: AdaptedLichen},
    {cardName: CardName.ADVANCED_ECOSYSTEMS, Factory: AdvancedEcosystems},
    {cardName: CardName.AEROBRAKED_AMMONIA_ASTEROID, Factory: AerobrakedAmmoniaAsteroid},
    {cardName: CardName.ANTS, Factory: Ants},
    {cardName: CardName.AQUIFER_PUMPING, Factory: AquiferPumping},
    {cardName: CardName.ALGAE, Factory: Algae},
    {cardName: CardName.ARCHAEBACTERIA, Factory: ArchaeBacteria},
    {cardName: CardName.ARCTIC_ALGAE, Factory: ArcticAlgae},
    {cardName: CardName.ARTIFICIAL_LAKE, Factory: ArtificialLake},
    {cardName: CardName.ARTIFICIAL_PHOTOSYNTHESIS, Factory: ArtificialPhotosynthesis},
    {cardName: CardName.ASTEROID, Factory: Asteroid},
    {cardName: CardName.ASTEROID_MINING, Factory: AsteroidMining},
    {cardName: CardName.BEAM_FROM_A_THORIUM_ASTEROID, Factory: BeamFromAThoriumAsteroid},
    {cardName: CardName.BIG_ASTEROID, Factory: BigAsteroid},
    {cardName: CardName.BIOMASS_COMBUSTORS, Factory: BiomassCombustors},
    {cardName: CardName.BIRDS, Factory: Birds},
    {cardName: CardName.BLACK_POLAR_DUST, Factory: BlackPolarDust},
    {cardName: CardName.BREATHING_FILTERS, Factory: BreathingFilters},
    {cardName: CardName.BUSHES, Factory: Bushes},
    {cardName: CardName.CAPITAL, Factory: Capital},
    {cardName: CardName.CARBONATE_PROCESSING, Factory: CarbonateProcessing},
    {cardName: CardName.CLOUD_SEEDING, Factory: CloudSeeding},
    {cardName: CardName.COLONIZER_TRAINING_CAMP, Factory: ColonizerTrainingCamp},
    {cardName: CardName.COMET, Factory: Comet},
    {cardName: CardName.CONVOY_FROM_EUROPA, Factory: ConvoyFromEuropa},
    {cardName: CardName.CUPOLA_CITY, Factory: CupolaCity},
    {cardName: CardName.DECOMPOSERS, Factory: Decomposers},
    {cardName: CardName.DEEP_WELL_HEATING, Factory: DeepWellHeating},
    {cardName: CardName.DEIMOS_DOWN, Factory: DeimosDown},
    {cardName: CardName.DESIGNED_MICRO_ORGANISMS, Factory: DesignedMicroOrganisms},
    {cardName: CardName.DOMED_CRATER, Factory: DomedCrater},
    {cardName: CardName.DUST_SEALS, Factory: DustSeals},
    {cardName: CardName.ECOLOGICAL_ZONE, Factory: EcologicalZone},
    {cardName: CardName.ENERGY_SAVING, Factory: EnergySaving},
    {cardName: CardName.EOS_CHASMA_NATIONAL_PARK, Factory: EosChasmaNationalPark},
    {cardName: CardName.EQUATORIAL_MAGNETIZER, Factory: EquatorialMagnetizer},
    {cardName: CardName.EXTREME_COLD_FUNGUS, Factory: ExtremeColdFungus},
    {cardName: CardName.FARMING, Factory: Farming},
    {cardName: CardName.FISH, Factory: Fish},
    {cardName: CardName.FLOODING, Factory: Flooding},
    {cardName: CardName.FOOD_FACTORY, Factory: FoodFactory},
    {cardName: CardName.FUSION_POWER, Factory: FusionPower},
    {cardName: CardName.FUELED_GENERATORS, Factory: FueledGenerators},
    {cardName: CardName.GANYMEDE_COLONY, Factory: GanymedeColony},
    {cardName: CardName.GEOTHERMAL_POWER, Factory: GeothermalPower},
    {cardName: CardName.GHG_FACTORIES, Factory: GHGFactories},
    {cardName: CardName.GHG_PRODUCING_BACTERIA, Factory: GHGProducingBacteria},
    {cardName: CardName.GIANT_ICE_ASTEROID, Factory: GiantIceAsteroid},
    {cardName: CardName.GIANT_SPACE_MIRROR, Factory: GiantSpaceMirror},
    {cardName: CardName.GRASS, Factory: Grass},
    {cardName: CardName.GREAT_DAM, Factory: GreatDam},
    {cardName: CardName.GREENHOUSES, Factory: Greenhouses},
    {cardName: CardName.HEATHER, Factory: Heather},
    {cardName: CardName.HEAT_TRAPPERS, Factory: HeatTrappers},
    {cardName: CardName.HERBIVORES, Factory: Herbivores},
    {cardName: CardName.ICE_ASTEROID, Factory: IceAsteroid},
    {cardName: CardName.ICE_CAP_MELTING, Factory: IceCapMelting},
    {cardName: CardName.IMMIGRANT_CITY, Factory: ImmigrantCity},
    {cardName: CardName.IMMIGRATION_SHUTTLES, Factory: ImmigrationShuttles},
    {cardName: CardName.IMPORTED_GHG, Factory: ImportedGHG},
    {cardName: CardName.IMPORTED_HYDROGEN, Factory: ImportedHydrogen},
    {cardName: CardName.IMPORTED_NITROGEN, Factory: ImportedNitrogen},
    {cardName: CardName.IMPORT_OF_ADVANCED_GHG, Factory: ImportOfAdvancedGHG},
    {cardName: CardName.INDUSTRIAL_MICROBES, Factory: IndustrialMicrobes},
    {cardName: CardName.INSECTS, Factory: Insects},
    {cardName: CardName.INSULATION, Factory: Insulation},
    {cardName: CardName.IRONWORKS, Factory: Ironworks},
    {cardName: CardName.KELP_FARMING, Factory: KelpFarming},
    {cardName: CardName.LAKE_MARINERIS, Factory: LakeMarineris},
    {cardName: CardName.LARGE_CONVOY, Factory: LargeConvoy},
    {cardName: CardName.LAVA_FLOWS, Factory: LavaFlows},
    {cardName: CardName.LICHEN, Factory: Lichen},
    {cardName: CardName.LIVESTOCK, Factory: Livestock},
    {cardName: CardName.LOCAL_HEAT_TRAPPING, Factory: LocalHeatTrapping},
    {cardName: CardName.LUNAR_BEAM, Factory: LunarBeam},
    {cardName: CardName.MAGNETIC_FIELD_DOME, Factory: MagneticFieldDome},
    {cardName: CardName.MAGNETIC_FIELD_GENERATORS, Factory: MagneticFieldGenerators},
    {cardName: CardName.MANGROVE, Factory: Mangrove},
    {cardName: CardName.MARTIAN_RAILS, Factory: MartianRails},
    {cardName: CardName.METHANE_FROM_TITAN, Factory: MethaneFromTitan},
    {cardName: CardName.MICRO_MILLS, Factory: MicroMills},
    {cardName: CardName.MINING_EXPEDITION, Factory: MiningExpedition},
    {cardName: CardName.MINING_RIGHTS, Factory: MiningRights},
    {cardName: CardName.MOHOLE_AREA, Factory: MoholeArea},
    {cardName: CardName.MOSS, Factory: Moss},
    {cardName: CardName.NATURAL_PRESERVE, Factory: NaturalPreserve},
    {cardName: CardName.NITRITE_REDUCING_BACTERIA, Factory: NitriteReducingBacteria},
    {cardName: CardName.NITROGEN_RICH_ASTEROID, Factory: NitrogenRichAsteroid},
    {cardName: CardName.NITROPHILIC_MOSS, Factory: NitrophilicMoss},
    {cardName: CardName.NOCTIS_CITY, Factory: NoctisCity},
    {cardName: CardName.NOCTIS_FARMING, Factory: NoctisFarming},
    {cardName: CardName.NUCLEAR_POWER, Factory: NuclearPower},
    {cardName: CardName.NUCLEAR_ZONE, Factory: NuclearZone},
    {cardName: CardName.OPEN_CITY, Factory: OpenCity},
    {cardName: CardName.OPTIMAL_AEROBRAKING, Factory: OptimalAerobraking},
    {cardName: CardName.ORE_PROCESSOR, Factory: OreProcessor},
    {cardName: CardName.PERMAFROST_EXTRACTION, Factory: PermafrostExtraction},
    {cardName: CardName.PEROXIDE_POWER, Factory: PeroxidePower},
    {cardName: CardName.PETS, Factory: Pets},
    {cardName: CardName.PHOBOS_SPACE_HAVEN, Factory: PhobosSpaceHaven},
    {cardName: CardName.PLANTATION, Factory: Plantation},
    {cardName: CardName.POWER_GRID, Factory: PowerGrid},
    {cardName: CardName.POWER_PLANT, Factory: PowerPlant},
    {cardName: CardName.PREDATORS, Factory: Predators},
    {cardName: CardName.PROTECTED_VALLEY, Factory: ProtectedValley},
    {cardName: CardName.RAD_CHEM_FACTORY, Factory: RadChemFactory},
    {cardName: CardName.REGOLITH_EATERS, Factory: RegolithEaters},
    {cardName: CardName.RELEASE_OF_INERT_GASES, Factory: ReleaseOfInertGases},
    {cardName: CardName.RESEARCH_OUTPOST, Factory: ResearchOutpost},
    {cardName: CardName.ROVER_CONSTRUCTION, Factory: RoverConstruction},
    {cardName: CardName.SEARCH_FOR_LIFE, Factory: SearchForLife},
    {cardName: CardName.SHUTTLES, Factory: Shuttles},
    {cardName: CardName.SMALL_ANIMALS, Factory: SmallAnimals},
    {cardName: CardName.SOIL_FACTORY, Factory: SoilFactory},
    {cardName: CardName.SOLAR_POWER, Factory: SolarPower},
    {cardName: CardName.SOLAR_WIND_POWER, Factory: SolarWindPower},
    {cardName: CardName.SOLETTA, Factory: Soletta},
    {cardName: CardName.SPACE_MIRRORS, Factory: SpaceMirrors},
    {cardName: CardName.SPECIAL_DESIGN, Factory: SpecialDesign},
    {cardName: CardName.STEELWORKS, Factory: Steelworks},
    {cardName: CardName.STRIP_MINE, Factory: StripMine},
    {cardName: CardName.SUBTERRANEAN_RESERVOIR, Factory: SubterraneanReservoir},
    {cardName: CardName.SYMBIOTIC_FUNGUS, Factory: SymbioticFungus},
    {cardName: CardName.TECTONIC_STRESS_POWER, Factory: TectonicStressPower},
    {cardName: CardName.TOWING_A_COMET, Factory: TowingAComet},
    {cardName: CardName.TREES, Factory: Trees},
    {cardName: CardName.TUNDRA_FARMING, Factory: TundraFarming},
    {cardName: CardName.UNDERGROUND_CITY, Factory: UndergroundCity},
    {cardName: CardName.UNDERGROUND_DETONATIONS, Factory: UndergroundDetonations},
    {cardName: CardName.URBANIZED_AREA, Factory: UrbanizedArea},
    {cardName: CardName.WATER_IMPORT_FROM_EUROPA, Factory: WaterImportFromEuropa},
    {cardName: CardName.WATER_SPLITTING_PLANT, Factory: WaterSplittingPlant},
    {cardName: CardName.WAVE_POWER, Factory: WavePower},
    {cardName: CardName.WINDMILLS, Factory: Windmills},
    {cardName: CardName.WORMS, Factory: Worms},
    {cardName: CardName.ZEPPELINS, Factory: Zeppelins},
  ],
  corporationCards: [
    {cardName: CardName.BEGINNER_CORPORATION, Factory: BeginnerCorporation},
    {cardName: CardName.CREDICOR, Factory: CrediCor},
    {cardName: CardName.ECOLINE, Factory: EcoLine},
    {cardName: CardName.HELION, Factory: Helion},
    {cardName: CardName.INTERPLANETARY_CINEMATICS, Factory: InterplanetaryCinematics},
    {cardName: CardName.INVENTRIX, Factory: Inventrix},
    {cardName: CardName.MINING_GUILD, Factory: MiningGuild},
    {cardName: CardName.PHOBOLOG, Factory: PhoboLog},
    {cardName: CardName.THARSIS_REPUBLIC, Factory: TharsisRepublic},
    {cardName: CardName.THORGATE, Factory: Thorgate},
    {cardName: CardName.UNITED_NATIONS_MARS_INITIATIVE, Factory: UnitedNationsMarsInitiative},
  ],
  standardProjects: [
    {cardName: CardName.AQUIFER_STANDARD_PROJECT, Factory: AquiferStandardProject},
    {cardName: CardName.CITY_STANDARD_PROJECT, Factory: CityStandardProject},
    {cardName: CardName.POWER_PLANT_STANDARD_PROJECT, Factory: PowerPlantStandardProject},
    {cardName: CardName.GREENERY_STANDARD_PROJECT, Factory: GreeneryStandardProject},
    {cardName: CardName.ASTEROID_STANDARD_PROJECT, Factory: AsteroidStandardProject},
    {cardName: CardName.SELL_PATENTS_STANDARD_PROJECT, Factory: SellPatentsStandardProject},
    {cardName: CardName.BUFFER_GAS_STANDARD_PROJECT, Factory: BufferGasStandardProject},
  ],
  standardActions: [
    {cardName: CardName.CONVERT_PLANTS, Factory: ConvertPlants},
    {cardName: CardName.CONVERT_HEAT, Factory: ConvertHeat},
  ],
});


export const CORP_ERA_CARD_MANIFEST = new CardManifest({
  module: 'corpera',
  projectCards: [
    {cardName: CardName.ACQUIRED_COMPANY, Factory: AcquiredCompany},
    {cardName: CardName.ADVANCED_ALLOYS, Factory: AdvancedAlloys},
    {cardName: CardName.AI_CENTRAL, Factory: AICentral},
    {cardName: CardName.ANTI_GRAVITY_TECHNOLOGY, Factory: AntiGravityTechnology},
    {cardName: CardName.ASTEROID_MINING_CONSORTIUM, Factory: AsteroidMiningConsortium},
    {cardName: CardName.BRIBED_COMMITTEE, Factory: BribedCommittee},
    {cardName: CardName.BUILDING_INDUSTRIES, Factory: BuildingIndustries},
    {cardName: CardName.BUSINESS_CONTACTS, Factory: BusinessContacts},
    {cardName: CardName.BUSINESS_NETWORK, Factory: BusinessNetwork},
    {cardName: CardName.CALLISTO_PENAL_MINES, Factory: CallistoPenalMines},
    {cardName: CardName.CARETAKER_CONTRACT, Factory: CaretakerContract},
    {cardName: CardName.CARTEL, Factory: Cartel},
    {cardName: CardName.CEOS_FAVORITE_PROJECT, Factory: CEOsFavoriteProject},
    {cardName: CardName.COMMERCIAL_DISTRICT, Factory: CommercialDistrict},
    {cardName: CardName.CORPORATE_STRONGHOLD, Factory: CorporateStronghold},
    {cardName: CardName.DEVELOPMENT_CENTER, Factory: DevelopmentCenter},
    {cardName: CardName.EARTH_CATAPULT, Factory: EarthCatapult},
    {cardName: CardName.EARTH_OFFICE, Factory: EarthOffice},
    {cardName: CardName.ELECTRO_CATAPULT, Factory: ElectroCatapult},
    {cardName: CardName.ENERGY_TAPPING, Factory: EnergyTapping},
    {cardName: CardName.FUEL_FACTORY, Factory: FuelFactory},
    {cardName: CardName.GENE_REPAIR, Factory: GeneRepair},
    {cardName: CardName.GREAT_ESCARPMENT_CONSORTIUM, Factory: GreatEscarpmentConsortium},
    {cardName: CardName.HACKERS, Factory: Hackers},
    {cardName: CardName.HIRED_RAIDERS, Factory: HiredRaiders},
    {cardName: CardName.INDENTURED_WORKERS, Factory: IndenturedWorkers},
    {cardName: CardName.INDUSTRIAL_CENTER, Factory: IndustrialCenter},
    {cardName: CardName.INTERSTELLAR_COLONY_SHIP, Factory: InterstellarColonyShip},
    {cardName: CardName.INVENTION_CONTEST, Factory: InventionContest},
    {cardName: CardName.INVENTORS_GUILD, Factory: InventorsGuild},
    {cardName: CardName.INVESTMENT_LOAN, Factory: InvestmentLoan},
    {cardName: CardName.IO_MINING_INDUSTRIES, Factory: IoMiningIndustries},
    {cardName: CardName.LAGRANGE_OBSERVATORY, Factory: LagrangeObservatory},
    {cardName: CardName.LAND_CLAIM, Factory: LandClaim},
    {cardName: CardName.LIGHTNING_HARVEST, Factory: LightningHarvest},
    {cardName: CardName.MARS_UNIVERSITY, Factory: MarsUniversity},
    {cardName: CardName.MASS_CONVERTER, Factory: MassConverter},
    {cardName: CardName.MEDIA_ARCHIVES, Factory: MediaArchives},
    {cardName: CardName.MEDIA_GROUP, Factory: MediaGroup},
    {cardName: CardName.MEDICAL_LAB, Factory: MedicalLab},
    {cardName: CardName.MINE, Factory: Mine},
    {cardName: CardName.MINERAL_DEPOSIT, Factory: MineralDeposit},
    {cardName: CardName.MINING_AREA, Factory: MiningArea},
    {cardName: CardName.MIRANDA_RESORT, Factory: MirandaResort},
    {cardName: CardName.OLYMPUS_CONFERENCE, Factory: OlympusConference},
    {cardName: CardName.PHYSICS_COMPLEX, Factory: PhysicsComplex},
    {cardName: CardName.POWER_INFRASTRUCTURE, Factory: PowerInfrastructure},
    {cardName: CardName.POWER_SUPPLY_CONSORTIUM, Factory: PowerSupplyConsortium},
    {cardName: CardName.PROTECTED_HABITATS, Factory: ProtectedHabitats},
    {cardName: CardName.QUANTUM_EXTRACTOR, Factory: QuantumExtractor},
    {cardName: CardName.RAD_SUITS, Factory: RadSuits},
    {cardName: CardName.RESEARCH, Factory: Research},
    {cardName: CardName.RESTRICTED_AREA, Factory: RestrictedArea},
    {cardName: CardName.ROBOTIC_WORKFORCE, Factory: RoboticWorkforce},
    {cardName: CardName.SABOTAGE, Factory: Sabotage},
    {cardName: CardName.SATELLITES, Factory: Satellites},
    {cardName: CardName.SECURITY_FLEET, Factory: SecurityFleet},
    {cardName: CardName.SPACE_ELEVATOR, Factory: SpaceElevator},
    {cardName: CardName.SPACE_STATION, Factory: SpaceStation},
    {cardName: CardName.SPONSORS, Factory: Sponsors},
    {cardName: CardName.STANDARD_TECHNOLOGY, Factory: StandardTechnology},
    {cardName: CardName.TARDIGRADES, Factory: Tardigrades},
    {cardName: CardName.TECHNOLOGY_DEMONSTRATION, Factory: TechnologyDemonstration},
    {cardName: CardName.TERRAFORMING_GANYMEDE, Factory: TerraformingGanymede},
    {cardName: CardName.TITANIUM_MINE, Factory: TitaniumMine},
    {cardName: CardName.TOLL_STATION, Factory: TollStation},
    {cardName: CardName.TRANS_NEPTUNE_PROBE, Factory: TransNeptuneProbe},
    {cardName: CardName.TROPICAL_RESORT, Factory: TropicalResort},
    {cardName: CardName.VESTA_SHIPYARD, Factory: VestaShipyard},
    {cardName: CardName.VIRAL_ENHANCERS, Factory: ViralEnhancers},
    {cardName: CardName.VIRUS, Factory: Virus},
  ],

  corporationCards: [
    {cardName: CardName.SATURN_SYSTEMS, Factory: SaturnSystems},
    {cardName: CardName.TERACTOR, Factory: Teractor},
  ]});
