export enum Tags {
    STEEL = "building",
    SPACE = "space",
    SCIENCE = "science",
    ENERGY = "power",
    EARTH = "earth",
    JOVIAN = "jovian",
    VENUS = "venus",
    PLANT = "plant",
    MICROBES = "microbe",
    ANIMAL = "animal",
    CITY = "city",
    WILDCARD = "wild",
    EVENT = "event",
}
